### ISSUE TITLE
Selenium are from google everytime recognized

### ISSUE THREAD

**Issue by Bastilla123** [thicccat688/selenium-recaptcha-solver#16]
**Describe the bug**
I setup a new project exactly like in this project description. I get always this error:

selenium_recaptcha_solver.exceptions.RecaptchaException: Google has detected automated queries. Try again later.

**To Reproduce**
Steps to reproduce the behaviour:
1. Setup project like in your description
2. Run it

**Expected behaviour**
Captcha are solved and google can't recognize that selenium control browser

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Chrome 113.0.5672.63 
 - Version 113.0.5672.63 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thicccat688** [comment]
Hey,

Sometimes Google ReCAPTCHA detects you're automating the solving of their challenges if you solve them too often or due to a bad IP reputation. 

Sadly, you can do nothing besides using a proxy (to get a different IP) or waiting for your IP to be cleared to solve the audio challenge. You can also utilise the built-in action delay functionality to slow the automated solving process, but if your IP is suspicious, it will only help a little.

I hope this answers your question for you. Have a nice day!
