### ISSUE TITLE
Unable to solve (perhaps related to iframe src?)

### ISSUE THREAD

**Issue by sambragg** [thicccat688/selenium-recaptcha-solver#22]
Hi dev, thanks for your hard work on this project!

I'm trying to solve the captcha [here](https://clientcenter.tradestation.com/) and it keeps timing out, despite me setting a lengthy delay_config. The button is able to be pressed so the challenge appears but then the next step (which I believe is to click the audio challenge button) never takes place.

I happened to notice in this project's source that the solver is waiting for an iframe with a different src to one found on the above login page (https://www.recaptcha.net/recaptcha/enterprise/bframe).

Any help appreciated!

**Comment by sambragg** [comment]
Fore completeness, here's my solver code:

`solver = RecaptchaSolver(driver=browser, delay_config=StandardDelayConfig(min_delay=5))
recaptcha_iframe = WebDriverWait(browser, timeout).until(
  EC.presence_of_element_located((By.XPATH, '//iframe[@title="reCAPTCHA"]')))
            
solver.click_recaptcha_v2(iframe=recaptcha_iframe)`

**Comment by sambragg** [comment]
Possibly related? #21

**Comment by sambragg** [comment]
Update: Changing the locator on line 83 of solver.py to `'iframe[src*="https://www.recaptcha.net/recaptcha/enterprise/bframe"]'` fixes the issue for me

**Comment by thicccat688** [comment]
Hi, 

Thanks for letting me know about this issue. I looked into it, and you're right; the issue comes from the iframe's src attribute. 

What I've done is change the logic to use `//iframe[contains(@src, "recaptcha") and contains(@src, "bframe")`. I've tested it for your example and issue #21, and it fixed it.

The site you're using has an interesting peculiarity where it has 2 ReCAPTCHA challenge iframes, one visible and the other hidden. Make sure you use something like `test_driver.find_elements(By.XPATH, '//iframe[@title="reCAPTCHA"]')[0]` to locate the correct challenge in your case.

I have deployed a new version of the package, so please let me know if any more issues arise. Have a nice day!

**Comment by sambragg** [comment]
Thanks for the fix and your hint about the two iframes, code now works flawlessly!
