### ISSUE TITLE
Why my captcha solver slower than the one in demo

### ISSUE THREAD

**Issue by Rylazius** [thicccat688/selenium-recaptcha-solver#28]
title

**Comment by thicccat688** [comment]
Hi,

There can be a variety of reasons why the solving process is slower for you than the one in the demo. 

Here are some of the most likely ones:
- You may be using StandardDelay with the ReCAPTCHA solver to make it slower and more human-like.
- The demo is a bit old now and things like human-like typing and longer delays to avoid detection have been added. 

I hope this answers your question. Have a nice day!

**Comment by Rylazius** [comment]
Soooooo, how to disable delay ?

**Comment by thicccat688** [comment]
There isn't functionality to turn off the base delays like human typing at the moment, and it's highly recommended not to disable it due to it helping a lot with avoiding detection from Google.

If you have a good use case, let me know, and I can implement a functionality to turn off human-like typing of audio prompts and other base delays.
